name: Terraform Plan

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  id-token: write

concurrency:
  group: terraform
  cancel-in-progress: true

jobs:
  terraform:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-1

      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.15.0
          terraform_wrapper: false

      - name: Terraform fmt
        run: terraform fmt -check -no-color -recursive

      - name: Initialise Terraform
        run: terraform init

      - name: Validate Terraform
        run: terraform validate

      - name: Plan Terraform
        id: plan
        run: terraform plan -out=terraform.plan

      - name: Show plan
        run: terraform show -no-color -json terraform.plan > terraform.json

      - uses: liatrio/terraform-change-pr-commenter@v1.14.2
        with:
          json-file: terraform.json
          log-changed-resources: false

      - name: Archive Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: terraform.plan
          if-no-files-found: error

